### ISSUE TITLE
Getting error when loading app

### ISSUE THREAD

**Issue by jadgsam** [masters1222/mm-music-player#7]
Please check the following error

Initializing mm-music-player module helper ...
WARNING! Could not load config file. Starting with default configuration. Error found: TypeError: m.loaded is not a function
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
No helper found for module: youtube.
Initializing new module helper ...
Module helper loaded: MMM-OnScreenMenu
No helper found for module: MMM-Globe.
Initializing mm-music-player module helper ...
Whoops! There was an uncaught exception...
TypeError: m.loaded is not a function
    at loadModule (/home/pi/MagicMirror/js/app.js:144:6)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:161:5)
    at /home/pi/MagicMirror/js/app.js:163:6
    at loadModule (/home/pi/MagicMirror/js/app.js:146:4)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:161:5)
    at /home/pi/MagicMirror/js/app.js:163:6
    at Class.loaded (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:19:3)
    at loadModule (/home/pi/MagicMirror/js/app.js:144:6)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:161:5)
    at /home/pi/MagicMirror/js/app.js:163:6
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by yazir-rizki** [comment]
me too

**Comment by DNA2010** [comment]
gets the same error
when magic mirror use the function no problems
var Module = require(helperPath);
{ [Function: Class] extend: [Function] }              for magic mirror
{ [Function: Class] extend: [Function], create: [Function] }        for mmm-music-player
----------------------------------------------------------------
-------Magic Mirror----------index.js----------setPath function
{ [Function: Class] extend: [Function] }
Class {
  name: 'updatenotification',
  path: '/home/pi/MagicMirror/modules/default/updatenotification' }
[Function: setName]
[Function: setPath]
[Function: push]
[Function]
=======================================
MMM-Music-Player ----------MMM-Music-Player.js-----------MODULE
MMM-Music-Player ----------- Node_Helper.js ---------var loaded
Initializing mm-music-player module helper ...
{ [Function: Class] extend: [Function], create: [Function] }
Class {
  name: 'mm-music-player',
  path: '/home/pi/MagicMirror/modules/mm-music-player' }
[Function: setName]
[Function: setPath]
[Function: push]
[Function]
WARNING! Could not load config file. Starting with default configuration. Error found: TypeError: m.loaded is not a function

**Comment by DNA2010** [comment]
if I comment out the m.loaded(callback) in the app.js file the magic mirror and music player loads onto
the screen with problems
not sure is value for module is causing the problem
magic mirror working fine
when setup the mmm music player module gets a error
magic mirror use the app.js with no problems 
{ [Function: Class] extend: [Function] }
Module vaule =          function Class() { // in the app.js file
============================================
mmm music player
{ [Function: Class] extend: [Function], create: [Function] }
Module vaule =          function Class() {
=============================================
code:
Initializing new module helper ...
-----------------------------------------VALUES------------------------------
loadModule value =      true
--------------------------------------------VALUES----------------------------
elements value =        newsfeed
-------------------------------------------VALUES-----------------------------
moduleName value =      newsfeed
----------------------------------------------VALUES--------------------------
moduleFolder value =    /home/pi/MagicMirror/js/../modules/default/newsfeed
---------------------------------------------VALUES---------------------------
loadModule value =      true
--------------------------------------------VALUES----------------------------
helperPath vaule =      /home/pi/MagicMirror/js/../modules/default/newsfeed/node_helper.js
---------------------------------------------VALUES---------------------------
{ [Function: Class] extend: [Function] }
Module vaule =          function Class() {
			// All construction is actually done in the init method
			if (!initializing && this.init) {
				this.init.apply(this, arguments);
			}
		}
----------------------------------------------VALUES--------------------------
m value =                 [object Object]
-----------------------------------------------VALUES-------------------------
m.setName value =         function(name) {
		this.name = name;
	}
------------------------------------------------VALUES------------------------
m.setPath value =         function(path) {

		this.path = path;

	}
------------------------------------------------VALUES------------------------
nodeHelpers.push value =  function push() { [native code] }
--------------------------------------------------VALUES----------------------
callback value =          function() {
					modules = modules.slice(1);
					loadNextModule();
				}
------------------------------------------------m.loaded(callback)-----------------------
-------Magic Mirror----------index.js----------loaded (callback) function
Module helper loaded: newsfeed

============================================================
when the mmm music player use the app.js gets a error
code:
Module helper loaded: newsfeed
[Function]
Initializing mm-music-player module helper ...
-----------------------------------------VALUES------------------------------
loadModule value =      true
--------------------------------------------VALUES----------------------------
elements value =        mm-music-player
-------------------------------------------VALUES-----------------------------
moduleName value =      mm-music-player
----------------------------------------------VALUES--------------------------
moduleFolder value =    /home/pi/MagicMirror/js/../modules/mm-music-player
---------------------------------------------VALUES---------------------------
loadModule value =      true
--------------------------------------------VALUES----------------------------
helperPath vaule =      /home/pi/MagicMirror/js/../modules/mm-music-player/node_helper.js
---------------------------------------------VALUES---------------------------
{ [Function: Class] extend: [Function], create: [Function] }
Module vaule =          function Class() {
			// All construction is actually done in the init method
			if (!initializing && this.init) {
				this.init.apply(this, arguments);
			}
		}
----------------------------------------------VALUES--------------------------
m value =                 [object Object]
-----------------------------------------------VALUES-------------------------
m.setName value =         function(name) {
		this.name = name;
	}
------------------------------------------------VALUES------------------------
m.setPath value =         function(path) {
		this.path = path;
	}
------------------------------------------------VALUES------------------------
nodeHelpers.push value =  function push() { [native code] }
--------------------------------------------------VALUES----------------------
callback value =          function() {
					modules = modules.slice(1);
					loadNextModule();
				}
------------------------------------------------m.loaded(callback)-----------------------
App threw an error during load
TypeError: m.loaded is not a function
    at loadModule (/home/pi/MagicMirror/js/app.js:191:41)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:223:5)
    at /home/pi/MagicMirror/js/app.js:225:6
    at Class.loaded (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:26:3)
    at loadModule (/home/pi/MagicMirror/js/app.js:191:41)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:223:5)
    at /home/pi/MagicMirror/js/app.js:225:6
    at loadModule (/home/pi/MagicMirror/js/app.js:202:4)
    at loadNextModule (/home/pi/MagicMirror/js/app.js:223:5)
    at /home/pi/MagicM
